Move experimental-features to settings in nix.nix
peanutbother/dotfiles pull request #1
Opened 2024-05-03 12:15 UTC by 497a

2024-05-03 15:52 UTC, peanutbother requested changes
thanks for the contribution!
I first have to test the effects / read on the docs as there might be semantic differences.
In a way to allow to override this parameter `lib.mkDefault` was used in the first place.
There exists a lib function which does the same for arrays but I have to look that up too, maybe you could read up on this?

2024-05-03 15:52 UTC, peanutbother commented on modules/common/nix.nix
> +      experimental-features = [ "nix-command" "flakes" ];
add `lib.mkDefault` or similar to allow overriding this setting

2024-05-03 23:26 UTC, 497a commented
Done!

2024-05-03 23:27 UTC, 497a commented
I built your config locally without any issues before committing.

2024-05-15 19:44 UTC, peanutbother approved these changes

2024-05-15 19:47 UTC, merged